#!/usr/bin/env bash
# =============================================================================
# deploy-prod.sh — massiveWiki production deployment script
#
# Run this after a fresh git clone on macOS or Linux.
# On Linux with systemd it will install/update the massivewiki.service unit.
# On macOS it starts the app directly (launchd support not included).
#
# Usage:
#   cd /path/to/massiveWiki
#   bash deploy/deploy-prod.sh
# =============================================================================

set -euo pipefail

# --- Configuration -----------------------------------------------------------
APP_PORT=3500
SERVICE_NAME="massivewiki"
SERVICE_FILE_REPO="$(cd "$(dirname "$0")" && pwd)/massivewiki.service"
SERVICE_FILE_INSTALLED="/etc/systemd/system/${SERVICE_NAME}.service"
APP_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CURRENT_USER="$(whoami)"

# Colours
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()      { echo -e "${GREEN}[ OK ]${NC}  $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
die()     { echo -e "${RED}[FAIL]${NC}  $*" >&2; exit 1; }

echo ""
echo "============================================================"
echo "  massiveWiki — production deployment"
echo "  App dir : $APP_DIR"
echo "  Port    : $APP_PORT"
echo "  User    : $CURRENT_USER"
echo "============================================================"
echo ""

# --- Detect OS ---------------------------------------------------------------
OS="$(uname -s)"
case "$OS" in
  Linux*)  PLATFORM="linux";;
  Darwin*) PLATFORM="macos";;
  *)       die "Unsupported OS: $OS";;
esac
info "Platform: $PLATFORM"

# --- Check required tools ----------------------------------------------------
info "Checking required tools..."

require_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" &>/dev/null; then
    die "Required command '$cmd' not found. Please install it and re-run."
  fi
  ok "  $cmd: $(command -v "$cmd")"
}

require_cmd git
require_cmd node
require_cmd npm

NODE_VER="$(node --version | sed 's/v//')"
NODE_MAJOR="${NODE_VER%%.*}"
if [ "$NODE_MAJOR" -lt 18 ]; then
  die "Node.js 18 or higher is required (found $NODE_VER)."
fi
ok "Node.js $NODE_VER"

# --- Verify we are in the right directory ------------------------------------
if [ ! -f "$APP_DIR/server.js" ] || [ ! -f "$APP_DIR/package.json" ]; then
  die "Cannot find server.js or package.json in $APP_DIR. Run this script from the repo root."
fi
ok "Repository looks good: $APP_DIR"

# --- Install npm dependencies ------------------------------------------------
info "Installing npm dependencies..."
cd "$APP_DIR"
npm install --omit=dev
ok "npm dependencies installed"

# --- Required directories ----------------------------------------------------
info "Checking required directories..."

for dir in wiki-data wiki-data/_wiki wiki-data/attachments public; do
  if [ ! -d "$APP_DIR/$dir" ]; then
    mkdir -p "$APP_DIR/$dir"
    ok "  Created: $dir"
  else
    ok "  Exists : $dir"
  fi
done

# --- .env setup --------------------------------------------------------------
ENV_FILE="$APP_DIR/.env"
ENV_EXAMPLE="$APP_DIR/.env.example"

if [ ! -f "$ENV_FILE" ]; then
  if [ -f "$ENV_EXAMPLE" ]; then
    cp "$ENV_EXAMPLE" "$ENV_FILE"
    warn ".env not found — copied from .env.example. Edit it before starting the app."
  else
    warn ".env not found and no .env.example to copy from. Creating a minimal .env."
    cat > "$ENV_FILE" <<ENVEOF
# massiveWiki production configuration
# Generated by deploy-prod.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
SUPABASE_URL=
SUPABASE_ANON_KEY=
SESSION_SECRET=
BASE_URL=
PORT=$APP_PORT
ENVEOF
  fi
fi

# Always set/override PORT to the hardcoded production port
if grep -q '^PORT=' "$ENV_FILE"; then
  if [ "$PLATFORM" = "macos" ]; then
    sed -i '' "s/^PORT=.*/PORT=$APP_PORT/" "$ENV_FILE"
  else
    sed -i "s/^PORT=.*/PORT=$APP_PORT/" "$ENV_FILE"
  fi
else
  echo "PORT=$APP_PORT" >> "$ENV_FILE"
fi
ok ".env updated — PORT=$APP_PORT"

# Require BASE_URL — prompt interactively if not already set
BASE_URL_VAL="$(grep '^BASE_URL=' "$ENV_FILE" | cut -d= -f2- | tr -d ' ')"
if [ -z "$BASE_URL_VAL" ]; then
  echo ""
  warn "BASE_URL is not set. This is required for the app to work behind a reverse proxy."
  echo "  Examples:"
  echo "    https://apps.example.com/wiki   (subpath deployment)"
  echo "    https://wiki.example.com        (root deployment)"
  echo ""
  read -r -p "  Enter public BASE_URL (leave blank to skip — set it manually in .env later): " BASE_URL_INPUT
  BASE_URL_INPUT="$(echo "$BASE_URL_INPUT" | tr -d ' ')"
  if [ -n "$BASE_URL_INPUT" ]; then
    if grep -q '^BASE_URL=' "$ENV_FILE"; then
      if [ "$PLATFORM" = "macos" ]; then
        sed -i '' "s|^BASE_URL=.*|BASE_URL=$BASE_URL_INPUT|" "$ENV_FILE"
      else
        sed -i "s|^BASE_URL=.*|BASE_URL=$BASE_URL_INPUT|" "$ENV_FILE"
      fi
    else
      echo "BASE_URL=$BASE_URL_INPUT" >> "$ENV_FILE"
    fi
    ok "BASE_URL set to: $BASE_URL_INPUT"
    BASE_URL_VAL="$BASE_URL_INPUT"
  else
    warn "BASE_URL not set — routing will break on subpath deployments."
    warn "Edit $ENV_FILE and set BASE_URL, then restart the service."
  fi
fi

# Remind about SESSION_SECRET
SESSION_VAL="$(grep '^SESSION_SECRET=' "$ENV_FILE" | cut -d= -f2- | tr -d ' ')"
if [ -z "$SESSION_VAL" ] || [ "$SESSION_VAL" = "your-random-secret-here" ]; then
  warn "SESSION_SECRET is not set — the server will auto-generate one on first start and save it to .env."
fi

# --- systemd service (Linux only) --------------------------------------------
if [ "$PLATFORM" = "linux" ] && command -v systemctl &>/dev/null; then
  info "Checking systemd service..."

  # Build the resolved service file from the template
  RESOLVED_SERVICE="$(mktemp /tmp/massivewiki.service.XXXXXX)"
  sed \
    -e "s|REPLACE_WITH_USER|$CURRENT_USER|g" \
    -e "s|REPLACE_WITH_APP_DIR|$APP_DIR|g" \
    "$SERVICE_FILE_REPO" > "$RESOLVED_SERVICE"

  NEEDS_INSTALL=false
  NEEDS_UPDATE=false

  if [ ! -f "$SERVICE_FILE_INSTALLED" ]; then
    NEEDS_INSTALL=true
  else
    # Compare the resolved template against the installed file
    if ! diff -q "$RESOLVED_SERVICE" "$SERVICE_FILE_INSTALLED" &>/dev/null; then
      NEEDS_UPDATE=true
    fi
  fi

  if $NEEDS_INSTALL; then
    info "Installing systemd service..."
    if [ "$(id -u)" -eq 0 ]; then
      cp "$RESOLVED_SERVICE" "$SERVICE_FILE_INSTALLED"
      chmod 644 "$SERVICE_FILE_INSTALLED"
      systemctl daemon-reload
      systemctl enable "$SERVICE_NAME"
      ok "Service installed and enabled."
    else
      info "Root required to install service. Attempting sudo..."
      sudo cp "$RESOLVED_SERVICE" "$SERVICE_FILE_INSTALLED"
      sudo chmod 644 "$SERVICE_FILE_INSTALLED"
      sudo systemctl daemon-reload
      sudo systemctl enable "$SERVICE_NAME"
      ok "Service installed and enabled."
    fi
  elif $NEEDS_UPDATE; then
    info "Repo service file differs from installed — updating..."
    if [ "$(id -u)" -eq 0 ]; then
      cp "$RESOLVED_SERVICE" "$SERVICE_FILE_INSTALLED"
      chmod 644 "$SERVICE_FILE_INSTALLED"
      systemctl daemon-reload
      ok "Service file updated and daemon reloaded."
    else
      sudo cp "$RESOLVED_SERVICE" "$SERVICE_FILE_INSTALLED"
      sudo chmod 644 "$SERVICE_FILE_INSTALLED"
      sudo systemctl daemon-reload
      ok "Service file updated and daemon reloaded."
    fi
  else
    ok "Installed service file is up to date."
  fi

  rm -f "$RESOLVED_SERVICE"

  # Start or restart the service
  info "Starting $SERVICE_NAME service..."
  if [ "$(id -u)" -eq 0 ]; then
    systemctl restart "$SERVICE_NAME"
    sleep 2
    systemctl is-active --quiet "$SERVICE_NAME" && ok "Service is running." || die "Service failed to start. Check: journalctl -u $SERVICE_NAME -n 50"
  else
    sudo systemctl restart "$SERVICE_NAME"
    sleep 2
    sudo systemctl is-active --quiet "$SERVICE_NAME" && ok "Service is running." || die "Service failed to start. Check: sudo journalctl -u $SERVICE_NAME -n 50"
  fi

elif [ "$PLATFORM" = "linux" ]; then
  warn "systemctl not found — skipping service installation."
  warn "Start the app manually: PORT=$APP_PORT node server.js"
fi

# --- macOS: just run the server in the foreground (or print instructions) ----
if [ "$PLATFORM" = "macos" ]; then
  echo ""
  echo "============================================================"
  echo "  macOS detected — no systemd available."
  echo ""
  echo "  To start the server:"
  echo "    cd $APP_DIR && node server.js"
  echo ""
  echo "  The server will listen on port $APP_PORT."
  echo "  Add a launchd plist or use a process manager like PM2 for"
  echo "  automatic startup on macOS."
  echo "============================================================"
fi

# --- Final summary -----------------------------------------------------------
echo ""
echo "============================================================"
ok "Deployment complete!"
echo ""
echo "  App dir : $APP_DIR"
echo "  Port    : $APP_PORT"
if [ -n "$BASE_URL_VAL" ]; then
  echo "  Base URL: $BASE_URL_VAL"
fi
echo ""
echo "  Next steps:"
echo "  1. Review and complete .env (especially BASE_URL and Supabase config)"
if [ "$PLATFORM" = "linux" ] && command -v systemctl &>/dev/null; then
  echo "  2. Visit the app and complete the admin setup wizard"
  echo "  3. Configure nginx using deploy/nginx.conf.example"
  echo "     sudo journalctl -u $SERVICE_NAME -f   (to tail logs)"
else
  echo "  2. Start the server:  cd $APP_DIR && node server.js"
  echo "  3. Visit the app at http://localhost:$APP_PORT and complete admin setup"
fi
echo "============================================================"
echo ""
